export const products = [
  {
    id: 1,
    image: 'src/assets/card001.png',
    name: 'Chinos',
    seller: '',
    amount: 5000,
  },
  {
    id: 2,
    image: 'src/assets/card003.png',
    name: 'Pure cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 3,
    image: 'src/assets/card002.png',
    name: 'Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 4,
    image: 'src/assets/card004.png',
    name: 'Black Chinos',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 5,
    image: 'src/assets/card5.png',
    name: 'Chinos',
    seller: '',
    amount: 5000,
  },
  {
    id: 6,
    image: 'src/assets/cardd4.png',
    name: 'Pure cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 7,
    image: 'src/assets/card7.png',
    name: 'Chinos & Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 8,
    image: 'src/assets/card6.png',
    name: 'Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 9,
    image: 'src/assets/card001.png',
    name: 'Chinos',
    seller: '',
    amount: 5000,
  },
  {
    id: 10,
    image: 'src/assets/card002.png',
    name: 'Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 11,
    image: 'src/assets/cardd003.png',
    name: 'Pure Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 12,
    image: 'src/assets/card004.png',
    name: 'Black Chinos',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 13,
    image: 'src/assets/card001.png',
    name: 'Chinos',
    seller: '',
    amount: 5000,
  },
  {
    id: 14,
    image: 'src/assets/card003.png',
    name: 'Pure cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 15,
    image: 'src/assets/card002.png',
    name: 'Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 16,
    image: 'src/assets/card004.png',
    name: 'Black Chinos',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 17,
    image: 'src/assets/card5.png',
    name: 'Chinos',
    seller: '',
    amount: 5000,
  },
  {
    id: 18,
    image: 'src/assets/cardd4.png',
    name: 'Pure cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 19,
    image: 'src/assets/card7.png',
    name: 'Chinos & Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 20,
    image: 'src/assets/card6.png',
    name: 'Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 21,
    image: 'src/assets/card001.png',
    name: 'Chinos',
    seller: '',
    amount: 5000,
  },
  {
    id: 22,
    image: 'src/assets/card002.png',
    name: 'Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 23,
    image: 'src/assets/cardd003.png',
    name: 'Pure Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 24,
    image: 'src/assets/card004.png',
    name: 'Black Chinos',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 25,
    image: 'src/assets/card6.png',
    name: 'Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 26,
    image: 'src/assets/card001.png',
    name: 'Chinos',
    seller: '',
    amount: 5000,
  },
  {
    id: 27,
    image: 'src/assets/card002.png',
    name: 'Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 28,
    image: 'src/assets/cardd003.png',
    name: 'Pure Cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 29,
    image: 'src/assets/card004.png',
    name: 'Black Chinos',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 30,
    image: 'src/assets/card001.png',
    name: 'Chinos',
    seller: '',
    amount: 5000,
  },
  {
    id: 31,
    image: 'src/assets/card003.png',
    name: 'Pure cotton',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
  {
    id: 32,
    image: 'src/assets/card004.png',
    name: 'Black Chinos',
    seller: 'by thetotebagshop',
    amount: 4000,
  },
];
